### ISSUE TITLE
Atlas Phenptype - Classification of existing Phenotypes

### ISSUE THREAD

**Issue by Hannah-Davies** [SwanseaUniversityMedical/concept-library#1481] opened 2023-12-06 10:25 UTC
### Specification
Store the definitions currently used for the prognostic Atlas in the Library as simple Phenotypes

### Status
Mostly blocked until data is available and https://github.com/SwanseaUniversityMedical/concept-library/issues/1409 is completed:

 Contact repository owner to get access to data

### Notes
Some differences between a 'Clinical Coded Phenotype' and an 'Atlas Phenotype':

The former is composed of one or more code lists, each of their own coding system, containing one or more codes
The latter is composed of a single 'Phecode' - defined as 'Phecodes are manually curated groups of International Classification of Diseases (ICD) codes intended to capture clinically meaningful concepts for research.'
To support Atlas Phenotypes, we will likely need a custom component on the create page to allow individuals to select a Coding System and an associated Phecode - in contrast to a Clinical Coded Phenotype, which allows the creation of Concepts.

### Tasks
**Classification of existing Phenotypes**

- [ ] Examine feasibility of implementing method to populate the category field for existing Clinical Phenotypes
- [ ]  Label the new phenotypes with the new classification categories in https://github.com/SwanseaUniversityMedical/concept-library/issues/1409

**Comment by DSThayer** [comment] 2024-07-11 10:18
Duplicate of #1614

**Closed by DSThayer** 2024-07-11 10:18 UTC
Labels: P2
